# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ALSBaselineCpp <- function(spectra, lambda = 6, p = 0.05, maxIter = 20L, n_threads = 1L) {
    .Call(`_RamEx_ALSBaselineCpp`, spectra, lambda, p, maxIter, n_threads)
}

calculateAUCParallel <- function(matrix, group, n_threads = 0L) {
    .Call(`_RamEx_calculateAUCParallel`, matrix, group, n_threads)
}

calculatePairedMarkersAUC <- function(matrix, group, threshold, batch_size = 1000L, n_threads = 0L) {
    .Call(`_RamEx_calculatePairedMarkersAUC`, matrix, group, threshold, batch_size, n_threads)
}

