# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculateAUCParallel <- function(matrix, group, n_threads = 0L) {
    .Call('_RamEx_calculateAUCParallel', PACKAGE = 'RamEx', matrix, group, n_threads)
}

calculatePairedMarkersAUC <- function(matrix, group, threshold, batch_size = 1000L, n_threads = 0L) {
    .Call('_RamEx_calculatePairedMarkersAUC', PACKAGE = 'RamEx', matrix, group, threshold, batch_size, n_threads)
}

