# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ALSBaselineCpp <- function(spectra, lambda = 6, p = 0.05, maxIter = 20L, n_threads = 1L) {
    .Call(`_RamEx_ALSBaselineCpp`, spectra, lambda, p, maxIter, n_threads)
}

SNIPBaselineCpp <- function(spectra, iterations = 100L, decreasing = FALSE, n_threads = 1L) {
    .Call(`_RamEx_SNIPBaselineCpp`, spectra, iterations, decreasing, n_threads)
}

ComputeSNN <- function(nn_ranked, prune) {
    .Call(`_RamEx_ComputeSNN`, nn_ranked, prune)
}

WriteEdgeFile <- function(snn, filename, display_progress) {
    invisible(.Call(`_RamEx_WriteEdgeFile`, snn, filename, display_progress))
}

DirectSNNToFile <- function(nn_ranked, prune, display_progress, filename) {
    .Call(`_RamEx_DirectSNNToFile`, nn_ranked, prune, display_progress, filename)
}

SNN_SmallestNonzero_Dist <- function(snn, mat, n, nearest_dist) {
    .Call(`_RamEx_SNN_SmallestNonzero_Dist`, snn, mat, n, nearest_dist)
}

calculateAUCParallel <- function(matrix, group, n_threads = 0L) {
    .Call(`_RamEx_calculateAUCParallel`, matrix, group, n_threads)
}

calculatePairedMarkersAUC <- function(matrix, group, threshold, batch_size = 1000L, n_threads = 0L) {
    .Call(`_RamEx_calculatePairedMarkersAUC`, matrix, group, threshold, batch_size, n_threads)
}

